# Generated by Django 5.0.7 on 2024-10-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
