# Generated by Django 5.0.7 on 2024-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantastic', 'Фантастика'), ('fantasy', 'Фэнтези'), ('horrors', 'Хорроры'), ('novels', 'Романы'), ('psychology', 'Психология'), ('history', 'История'), ('detectives', 'Детективы'), ('russian_classics', 'Отечественная класика'), ('foreign_classics', 'Зарубежная класика'), ('biography', 'Биография'), ('self_development', 'Саморазвитие'), ('prose', 'Проза'), ('business', 'Бизнес')], max_length=50, null=True),
        ),
    ]
