# Generated by Django 5.0.7 on 2024-10-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fantastic', 'Фантастика'), ('fantasy', 'Фэнтези'), ('horrors', 'Хорроры'), ('novels', 'Романы'), ('psychology', 'Психология'), ('history', 'История'), ('detectives', 'Детективы'), ('russian_classics', 'Отечественная класика'), ('foreign_classics', 'Зарубежная класика'), ('biography', 'Биография'), ('self_development', 'Саморазвитие'), ('prose', 'Проза'), ('business', 'Бизнес')], max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.book')),
            ],
        ),
    ]
