# Generated by Django 5.0.7 on 2024-10-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_genre_bookgenrerelation_delete_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('fantastic', 'Фантастика'), ('fantasy', 'Фэнтези'), ('horrors', 'Хорроры'), ('novels', 'Романы'), ('psychology', 'Психология'), ('history', 'История'), ('detectives', 'Детективы'), ('russian_classics', 'Отечественная класика'), ('foreign_classics', 'Зарубежная класика'), ('biography', 'Биография'), ('self_development', 'Саморазвитие'), ('prose', 'Проза'), ('business', 'Бизнес'), ('drama', 'Драма')], default='', max_length=50),
        ),
    ]
