# Generated by Django 5.0.7 on 2024-10-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_book_genre_alter_genre_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genre_old',
        ),
    ]
