# Generated by Django 5.0.7 on 2024-10-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_rename_genre_book_genre_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre_old',
        ),
    ]
