# Generated by Django 5.0.7 on 2024-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_remove_book_genre_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book_app.genre'),
        ),
    ]
