# Generated by Django 5.0.7 on 2024-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_remove_book_top_100_book_bestseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookGenreRelation',
        ),
    ]
