# Generated by Django 5.0.7 on 2024-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_alter_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpicture',
            name='picture',
            field=models.ImageField(default='media/book_covers/default_book_cover.jpg', upload_to='book_covers/'),
        ),
    ]
