# Generated by Django 5.0.7 on 2024-10-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_alter_bookpicture_picture_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpicture',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='book_app.book'),
        ),
    ]
