# Generated by Django 5.0.7 on 2024-10-10 14:49

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0019_alter_author_full_name_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='EBookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='ebooks'), upload_to='ebooks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_app.book')),
            ],
        ),
    ]
