# Generated by Django 5.0.7 on 2024-10-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0020_alter_book_slug_ebookfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookfile',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebookfile',
            name='file_type',
            field=models.CharField(choices=[('F', 'FB2'), ('E', 'EPUB'), ('D', 'DOC')], max_length=1, null=True),
        ),
    ]
