# Generated by Django 5.0.7 on 2024-10-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0021_ebookfile_file_size_ebookfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookfile',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.book'),
        ),
        migrations.AlterField(
            model_name='ebookfile',
            name='file_type',
            field=models.CharField(choices=[('F', 'FB2'), ('E', 'EPUB'), ('D', 'DOC'), ('P', 'PDF'), ('T', 'TXT'), ('R', 'RTF')], max_length=1, null=True),
        ),
    ]
