# Generated by Django 5.0.7 on 2024-10-12 06:45

import book_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0022_alter_ebookfile_book_alter_ebookfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookfile',
            name='ebook',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='content/ebooks'), upload_to=book_app.models.get_upload_path),
        ),
    ]
