# Generated by Django 5.0.7 on 2024-10-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0023_alter_ebookfile_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='Автор', null=True, on_delete=django.db.models.deletion.CASCADE, to='book_app.author'),
        ),
    ]
