# Generated by Django 5.0.7 on 2024-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0026_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='user_profile_photo/default_profile_photo.jpg', null=True, upload_to='user_profile_photo/'),
        ),
    ]
