# Generated by Django 5.0.7 on 2024-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0027_alter_user_password_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='user_profile_photo/default_profile_photo.jpg', upload_to='user_profile_photo/'),
        ),
    ]
